export const FETCH_COUNT_SMS_START = 'FETCH_COUNT_SMS_START';
export const FETCH_COUNT_SMS_SUCCESS = 'FETCH_COUNT_SMS_SUCCESS';
export const FETCH_COUNT_ERROR = 'FETCH_COUNT_ERROR';

export const CREATE_SMS_START = 'CREATE_SMS_START';
export const CREATE_SMS_SUCCESS = 'CREATE_SMS_SUCCESS';
export const CREATE_SMS_ERROR = 'CREATE_SMS_ERROR';
